export const vaultManagerAbi = [
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "deposit",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "requestWithdrawal",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "redeem",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ name: "assets", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "withdrawalDelay",
    inputs: [],
    outputs: [{ name: "delay", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getVaultState",
    inputs: [],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "vault", type: "address" },
          { name: "totalAssets", type: "uint256" },
          { name: "totalSupply", type: "uint256" },
          { name: "reserveAssets", type: "uint256" },
          { name: "aaveDeployedAssets", type: "uint256" },
          { name: "openLiability", type: "uint256" },
          { name: "availableLiability", type: "uint256" },
          { name: "sharePriceE18", type: "uint256" },
          { name: "utilizationBps", type: "uint256" },
          { name: "active", type: "bool" },
          { name: "withdrawalsBlocked", type: "bool" },
          { name: "aaveEnabled", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getPendingWithdrawal",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "assets", type: "uint256" },
      { name: "shares", type: "uint256" },
      { name: "unlockTimestamp", type: "uint64" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "maxRedeem",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "maxWithdraw",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "assets", type: "uint256" }],
  },
] as const;
